name: Validate JSONs

on: [pull_request, push]

jobs:
  verify-rules-json-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /data/schemas/category.schema.json
          INPUT_JSONS: /data/rules/agile-health.rules.json